 
version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=udyamdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d udyamdb"]
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build: .
    environment:
      - postgresql://postgres:QHSGcCILmBNyqcgJcvReKCOWulcAzixb@postgres.railway.internal:5432/railway
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - .:/app

volumes:
  postgres_data: